2025/04/22 14:55:10 [error] 30#30: *1 connect() failed (113: Host is unreachable) while connecting to upstream, client: 172.28.0.1, server: localhost, request: "GET /api/users?page=1 HTTP/1.1", upstream: "fastcgi://172.28.0.2:9000", host: "localhost", referrer: "http://localhost/api"
2025/04/22 14:55:18 [error] 30#30: *1 connect() failed (113: Host is unreachable) while connecting to upstream, client: 172.28.0.1, server: localhost, request: "GET /api/users?page=1 HTTP/1.1", upstream: "fastcgi://172.28.0.2:9000", host: "localhost", referrer: "http://localhost/api"
2025/04/22 14:55:26 [error] 30#30: *1 connect() failed (113: Host is unreachable) while connecting to upstream, client: 172.28.0.1, server: localhost, request: "GET /api HTTP/1.1", upstream: "fastcgi://172.28.0.2:9000", host: "localhost"
2025/04/29 17:17:33 [error] 32#32: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.28.0.1, server: localhost, request: "POST /api/auth/request-code HTTP/1.1", upstream: "fastcgi://172.28.0.2:9000", host: "localhost", referrer: "http://localhost/api/login"
2025/04/29 17:17:36 [error] 31#31: *3 connect() failed (111: Connection refused) while connecting to upstream, client: 172.28.0.1, server: localhost, request: "POST /api/auth/request-code HTTP/1.1", upstream: "fastcgi://172.28.0.2:9000", host: "localhost", referrer: "http://localhost/api/login"
2025/04/29 17:17:42 [error] 31#31: *3 connect() failed (111: Connection refused) while connecting to upstream, client: 172.28.0.1, server: localhost, request: "GET /api/login HTTP/1.1", upstream: "fastcgi://172.28.0.2:9000", host: "localhost"
2025/04/29 17:17:52 [error] 32#32: *8 connect() failed (111: Connection refused) while connecting to upstream, client: 172.28.0.1, server: localhost, request: "GET /api/login HTTP/1.1", upstream: "fastcgi://172.28.0.2:9000", host: "localhost"
2025/04/29 17:18:02 [error] 31#31: *11 connect() failed (111: Connection refused) while connecting to upstream, client: 172.28.0.1, server: localhost, request: "GET /api/login HTTP/1.1", upstream: "fastcgi://172.28.0.2:9000", host: "localhost"
2025/04/29 17:18:05 [error] 32#32: *13 connect() failed (111: Connection refused) while connecting to upstream, client: 172.28.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://172.28.0.2:9000", host: "localhost", referrer: "http://localhost/api/login"
2025/04/29 17:20:58 [error] 32#32: *16 connect() failed (111: Connection refused) while connecting to upstream, client: 172.28.0.1, server: localhost, request: "GET /api/login HTTP/1.1", upstream: "fastcgi://172.28.0.2:9000", host: "localhost"
2025/04/29 17:21:00 [error] 32#32: *16 connect() failed (111: Connection refused) while connecting to upstream, client: 172.28.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://172.28.0.2:9000", host: "localhost", referrer: "http://localhost/api/login"
2025/04/29 17:27:59 [error] 29#29: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.28.0.1, server: localhost, request: "GET /api/login HTTP/1.1", upstream: "fastcgi://172.28.0.2:9000", host: "localhost"
2025/04/29 17:28:01 [error] 29#29: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.28.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://172.28.0.2:9000", host: "localhost", referrer: "http://localhost/api/login"
2025/04/29 17:28:48 [error] 30#30: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.28.0.1, server: localhost, request: "GET /api/login HTTP/1.1", upstream: "fastcgi://172.28.0.3:9000", host: "localhost"
